Downgrade PyJWT to 1.7.1, to avoid dependency problems:
    ERROR: After October 2020 you may experience errors when installing or updating packages. This is because pip will change the way that it resolves dependency conflicts.

    We recommend you use --use-feature=2020-resolver to test your packages with the new resolver before it becomes the default.

    pygithub 1.54.1 requires pyjwt<2.0, but you'll have pyjwt 2.0.1 which is incompatible.
djangorestframework-jwt 1.11.0 requires PyJWT<2.0.0,>=1.5.2, but you'll have pyjwt 2.0.1 which is incompatible.